<?xml version="1.0" encoding="utf-8"?><Database Name="Cinema1" Class="CinemaLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NDPHU-PC;Initial Catalog=Cinema1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Cinema1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BinhLuan" Member="BinhLuans">
    <Type Name="BinhLuan">
      <Column Name="MaBinhLuan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaPhim" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoiDungBinhLuan" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DanhMucTinhTrangBinhLuan_BinhLuan" Member="DanhMucTinhTrangBinhLuan" ThisKey="TinhTrang" OtherKey="MaTinhTrang" Type="DanhMucTinhTrangBinhLuan" IsForeignKey="true" />
      <Association Name="NguoiDung_BinhLuan" Member="NguoiDung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="Phim_BinhLuan" Member="Phim" ThisKey="MaPhim" OtherKey="MaPhim" Type="Phim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="MaVe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDatVe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DatVe_Ve" Member="DatVe" ThisKey="MaDatVe" OtherKey="MaDatVe" Type="DatVe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucGhe" Member="DanhMucGhes">
    <Type Name="DanhMucGhe">
      <Column Name="MaDanhMucGhe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMucGhe" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GiaDanhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DanhMucGhe_Ghe" Member="Ghes" ThisKey="MaDanhMucGhe" OtherKey="MaDanhMucGhe" Type="Ghe" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucLoaiPhim" Member="DanhMucLoaiPhims">
    <Type Name="DanhMucLoaiPhim">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GiaDanhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DanhMucLoaiPhim_Phim" Member="Phims" ThisKey="MaLoai" OtherKey="LoaiPhim" Type="Phim" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucNgayTrongTuan" Member="DanhMucNgayTrongTuans">
    <Type Name="DanhMucNgayTrongTuan">
      <Column Name="MaDanhMuc" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNgay" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NoiDungKhuyenMai" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GiaDanhMuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucNguoiDung" Member="DanhMucNguoiDungs">
    <Type Name="DanhMucNguoiDung">
      <Column Name="MaDanhMucNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMucNguoiDung" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DanhMucNguoiDung_NguoiDung" Member="NguoiDungs" ThisKey="MaDanhMucNguoiDung" OtherKey="MaDanhMucNguoiDung" Type="NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucSuatChieu" Member="DanhMucSuatChieus">
    <Type Name="DanhMucSuatChieu">
      <Column Name="MaDanhMucSuatChieu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThoiGianBatDau" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GiaDanhMuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DanhMucSuatChieu_SuatChieu" Member="SuatChieus" ThisKey="MaDanhMucSuatChieu" OtherKey="MaDanhMucSuatChieu" Type="SuatChieu" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucTheLoaiPhim" Member="DanhMucTheLoaiPhims">
    <Type Name="DanhMucTheLoaiPhim">
      <Column Name="MaDanhMucTheLoaiPhim" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMucTheLoaiPhim" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DanhMucTheLoaiPhim_Phim" Member="Phims" ThisKey="MaDanhMucTheLoaiPhim" OtherKey="TheLoai" Type="Phim" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucTinhTrangBinhLuan" Member="DanhMucTinhTrangBinhLuans">
    <Type Name="DanhMucTinhTrangBinhLuan">
      <Column Name="MaTinhTrang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTinhTrang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DanhMucTinhTrangBinhLuan_BinhLuan" Member="BinhLuans" ThisKey="MaTinhTrang" OtherKey="TinhTrang" Type="BinhLuan" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucTinhTrangNguoiDung" Member="DanhMucTinhTrangNguoiDungs">
    <Type Name="DanhMucTinhTrangNguoiDung">
      <Column Name="MaDanhMucTinhTrangNguoDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMucTinhTrangNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DanhMucTinhTrangNguoiDung_NguoiDung" Member="NguoiDungs" ThisKey="MaDanhMucTinhTrangNguoDung" OtherKey="TinhTrang" Type="NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.DatVe" Member="DatVes">
    <Type Name="DatVe">
      <Column Name="MaDatVe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaGhe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiDiemDat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaVe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaSuatChieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DatVe_Ve" Member="Ves" ThisKey="MaDatVe" OtherKey="MaDatVe" Type="Ve" />
      <Association Name="Ghe_DatVe" Member="Ghe" ThisKey="MaGhe" OtherKey="MaGhe" Type="Ghe" IsForeignKey="true" />
      <Association Name="NguoiDung_DatVe" Member="NguoiDung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="SuatChieu_DatVe" Member="SuatChieu" ThisKey="MaSuatChieu" OtherKey="MaSuatChieu" Type="SuatChieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ghe" Member="Ghes">
    <Type Name="Ghe">
      <Column Name="MaGhe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhongChieuPhim" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenGhe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaDanhMucGhe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Hang" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="SoThuTu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Ghe_DatVe" Member="DatVes" ThisKey="MaGhe" OtherKey="MaGhe" Type="DatVe" />
      <Association Name="DanhMucGhe_Ghe" Member="DanhMucGhe" ThisKey="MaDanhMucGhe" OtherKey="MaDanhMucGhe" Type="DanhMucGhe" IsForeignKey="true" />
      <Association Name="PhongChieuPhim_Ghe" Member="PhongChieuPhim" ThisKey="MaPhongChieuPhim" OtherKey="MaPhongChieuPhim" Type="PhongChieuPhim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichChieuPhim" Member="LichChieuPhims">
    <Type Name="LichChieuPhim">
      <Column Name="MaLichChieuPhim" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayChieu" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LichChieuPhim_SuatChieu" Member="SuatChieus" ThisKey="MaLichChieuPhim" OtherKey="MaLichChieu" Type="SuatChieu" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuNguoiDung" Member="LichSuNguoiDungs">
    <Type Name="LichSuNguoiDung">
      <Column Name="MaLichSuNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TongThoiGianDangNhap" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianDangNhapGanNhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianDangKi" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ThongTinKhac" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NguoiDung_LichSuNguoiDung" Member="NguoiDung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDanhMucNguoiDung" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNguoiDung" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NguoiDung_BinhLuan" Member="BinhLuans" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="BinhLuan" />
      <Association Name="NguoiDung_DatVe" Member="DatVes" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="DatVe" />
      <Association Name="NguoiDung_LichSuNguoiDung" Member="LichSuNguoiDungs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="LichSuNguoiDung" />
      <Association Name="DanhMucNguoiDung_NguoiDung" Member="DanhMucNguoiDung" ThisKey="MaDanhMucNguoiDung" OtherKey="MaDanhMucNguoiDung" Type="DanhMucNguoiDung" IsForeignKey="true" />
      <Association Name="DanhMucTinhTrangNguoiDung_NguoiDung" Member="DanhMucTinhTrangNguoiDung" ThisKey="TinhTrang" OtherKey="MaDanhMucTinhTrangNguoDung" Type="DanhMucTinhTrangNguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phim" Member="Phims">
    <Type Name="Phim">
      <Column Name="MaPhim" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhim" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TheLoai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DaoDien" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienVienThamGia" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NgonNgu" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiLuong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DiemDanhGia" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnhPhim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TrailerPhim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LoaiPhim" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Phim_BinhLuan" Member="BinhLuans" ThisKey="MaPhim" OtherKey="MaPhim" Type="BinhLuan" />
      <Association Name="Phim_SuatChieu" Member="SuatChieus" ThisKey="MaPhim" OtherKey="MaPhim" Type="SuatChieu" />
      <Association Name="DanhMucLoaiPhim_Phim" Member="DanhMucLoaiPhim" ThisKey="LoaiPhim" OtherKey="MaLoai" Type="DanhMucLoaiPhim" IsForeignKey="true" />
      <Association Name="DanhMucTheLoaiPhim_Phim" Member="DanhMucTheLoaiPhim" ThisKey="TheLoai" OtherKey="MaDanhMucTheLoaiPhim" Type="DanhMucTheLoaiPhim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongChieuPhim" Member="PhongChieuPhims">
    <Type Name="PhongChieuPhim">
      <Column Name="MaPhongChieuPhim" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaRapChieuPhim" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenPhongChieuPhim" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TongSoLuongGhe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PhongChieuPhim_Ghe" Member="Ghes" ThisKey="MaPhongChieuPhim" OtherKey="MaPhongChieuPhim" Type="Ghe" />
      <Association Name="PhongChieuPhim_SuatChieu" Member="SuatChieus" ThisKey="MaPhongChieuPhim" OtherKey="MaPhong" Type="SuatChieu" />
      <Association Name="RapChieuPhim_PhongChieuPhim" Member="RapChieuPhim" ThisKey="MaRapChieuPhim" OtherKey="MaRapChieuPhim" Type="RapChieuPhim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RapChieuPhim" Member="RapChieuPhims">
    <Type Name="RapChieuPhim">
      <Column Name="MaRapChieuPhim" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenRapChieuPhim" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChiRapChieuPhim" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoaiRapChieuPhim" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AnhDaiDienRapChieuPhim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThongTinKhac" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="RapChieuPhim_PhongChieuPhim" Member="PhongChieuPhims" ThisKey="MaRapChieuPhim" OtherKey="MaRapChieuPhim" Type="PhongChieuPhim" />
    </Type>
  </Table>
  <Table Name="dbo.SuatChieu" Member="SuatChieus">
    <Type Name="SuatChieu">
      <Column Name="MaSuatChieu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLichChieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaPhim" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaDanhMucSuatChieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SuatChieu_DatVe" Member="DatVes" ThisKey="MaSuatChieu" OtherKey="MaSuatChieu" Type="DatVe" />
      <Association Name="DanhMucSuatChieu_SuatChieu" Member="DanhMucSuatChieu" ThisKey="MaDanhMucSuatChieu" OtherKey="MaDanhMucSuatChieu" Type="DanhMucSuatChieu" IsForeignKey="true" />
      <Association Name="LichChieuPhim_SuatChieu" Member="LichChieuPhim" ThisKey="MaLichChieu" OtherKey="MaLichChieuPhim" Type="LichChieuPhim" IsForeignKey="true" />
      <Association Name="Phim_SuatChieu" Member="Phim" ThisKey="MaPhim" OtherKey="MaPhim" Type="Phim" IsForeignKey="true" />
      <Association Name="PhongChieuPhim_SuatChieu" Member="PhongChieuPhim" ThisKey="MaPhong" OtherKey="MaPhongChieuPhim" Type="PhongChieuPhim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThamSo" Member="ThamSos">
    <Type Name="ThamSo">
      <Column Name="MaThamSo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThamSo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Kieu" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>